clc;
clear;
clear all;
n=0:10;
x=10*((-0.1)+(0.2*1i*pi))*n;
[xe,xo,neo]=evenodd(x,n);
real_xe=real(xe); imag_xe=imag(xe); real_xo=real(xo); imag_xo=imag(xo);
subplot(2,3,1);
stem(neo,xe);
title("Even Part");
subplot(2,3,2);
stem(neo,real_xe);
title("Real Even Part");
subplot(2,3,3);
stem(neo,imag_xe); 
title("Imaginary Even Part");
subplot(2,3,4);
stem(neo,xo);
title("Odd Part");
subplot(2,3,5);
stem(neo,real_xo);
title("Real Odd Part");
subplot(2,3,6);
stem(neo,imag_xo);
title("İmaginary Odd Part");
